---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: santoshbd67/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: database-1.chq2k6qs0ud6.us-east-1.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: crud_app

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: prod
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
